### PR TITLE
Big Refactor and retheme

### PR DESCRIPTION
**Pull request by jwu910**
Big refactor and retheme

### CODE REVIEW

**Comment by jwu910** [comment]
Dude, looking pretty good @phuchle

**Review by phuchle — CHANGES_REQUESTED** [review]
If I keep pressing for a free ticket, it just keeps going faster and then doesn't stop. The spinning animation is also lost.  Probably have to set a flag for if the button has been pressed already and handling the situation of multiple presses.

**Comment by jwu910** [comment]
Great idea, i was wondering what i was gonna do. Ill update and commit.

**Comment by jwu910** [comment]
This one we can squash and merge when ready* Lots of fluff commits to fix stuff.

**Review by phuchle — APPROVED** [review]

**Pull request merged**
